### ISSUE TITLE
Request example of passing parameters to provider=custom

### ISSUE THREAD

**Issue by DrDaveD** [puppetlabs/vault-plugin-secrets-oauthapp#5]
This plugin appears to be just about all that I'm looking for.  However I haven't been able to figure out how to pass the options to the custom provider from the vault command line.   Could you please provide an example?

**Comment by DrDaveD** [comment]
It looks like I was able to figure it out:
```
echo -n '{"provider_options": {"auth_code_url": "...", "token_url": "..."}}'| \
    vault write oauthapp/config   provider=custom -  client_id="..."     client_secret="..."
```
I don't know if there's a simpler way, but it would be good to document this.

**Comment by impl** [comment]
We'll put some relevant docs in about this. Thanks for reporting!

**Comment by impl** [comment]
I fixed this when I was updating some additional relevant documentation as part of #22. Thanks!
