### ISSUE TITLE
Set a default server to make v2 to v3 upgrades easier

### ISSUE THREAD

**Issue by impl** [puppetlabs/vault-plugin-secrets-oauthapp#62]
## Use Case

It can be inconvenient to have to modify all clients to write credentials with a new option, especially if the clients are distributed across workstation machines. Therefore, we should have some way to bypass that requirement for uggprading users.

## Describe the Solution You Would Like

Add a `default_server` option to the plugin config.

## Describe Alternatives You've Considered

* The plugin could automatically make "legacy" the default server if it exists and is the only defined server.
* The plugin could flag v2 to v3 a migration and only allow the single upgraded server to be the default.

## Additional Context

See discussion in #60.

**Comment by DrDaveD** [comment]
I like the alternative of making "legacy" be the default server if no other servers are defined.  Or yet another alternative I like even better is to make the server option be optional if there is only one server defined.  That would also be helpful for people who want to still stick with only one server per module instance, whether they migrated from v2 or not.

**Comment by DrDaveD** [comment]
I would like to be able to move forward with using v3, and this is blocking me.  If you can give me some hints on how to implement it, I will work on making a PR.

**Comment by DrDaveD** [comment]
I made an attempt in #64.
