### ISSUE TITLE
Add a way to list the currently configured servers

### ISSUE THREAD

**Issue by DrDaveD** [puppetlabs/vault-plugin-secrets-oauthapp#65]
## Use Case
I would like to have a way to read back a list of which servers are configured in a multi-authorization server mode, analogous to 'vault secrets list' when there's a module for each server.

## Describe the Solution You Would Like
Perhaps `vault read secret/oauthapp/servers` or `vault list secret/oauthapp/servers` could return a list of the server names

**Comment by impl** [comment]
This is a fine idea, except that we don't actually currently store the names anywhere, just their hashes. But since we're just in beta, I think I'm comfortable breaking existing installs so that information can be added, as long as it's cool with you.

**Comment by DrDaveD** [comment]
Yes I think that will be ok, especially if it's done soon.  I have actually tagged a release of my code using the beta, but it's not fully released and anyway there's only two other people who install my code for testing so far besides me so it's not too hard for me to get everything quickly updated.  I do have about a half dozen other people who are also using one of my servers for testing, but nothing is in production use yet so a little disruption isn't so bad.  The harder part is getting all the testers to update their clients in a short amount of time, so that's why backward compatibility on the API is desired.

**Comment by impl** [comment]
Makes sense. I'm going to try to get this out today.
